org.gradle.jvmargs=-Xmx4G
android.useAndroidX=true
android.enableJetifier=true
RELEASE_STORE_FILE=../upload-keystore.jks
RELEASE_STORE_PASSWORD=ncadvance
RELEASE_KEY_ALIAS=ncadvance
RELEASE_KEY_PASSWORD=ncadvance
android.defaults.buildfeatures.buildconfig=true
android.nonTransitiveRClass=false
android.nonFinalResIds=false
# This builtInKotlin flag was added automatically by Flutter migrator
android.builtInKotlin=false
# This newDsl flag was added automatically by Flutter migrator
android.newDsl=false
